services:
  - type: web
    name: mindmapper-backend
    env: node
    plan: free
    buildCommand: npm install --ignore-scripts
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium-browser